"""Data model for a Marcos OS Morning Brief."""

from dataclasses import dataclass, field
from datetime import datetime

from models.recommendation import Recommendation


@dataclass
class MorningBrief:
    """A structured daily briefing generated by Marcos OS.

    The MorningBrief is the primary human-facing output of a single
    ExecutiveEngine run cycle. It aggregates all recommendations produced
    by the executive team into a single deliverable.

    Future evolution:
        - Delivered via Telegram when the integration is connected.
        - Persisted to PostgreSQL for historical review.
        - Enriched by OpenRouter LLM reasoning when the AI layer is active.
        - Surfaced on a Dashboard when the frontend is built.
        - Augmented with Home Assistant context when that integration is live.

    Attributes:
        generated_at: UTC timestamp when this brief was generated.
        recommendations: Priority-sorted list of Recommendation objects.
        summary: Human-readable summary of the brief content.
        total_recommendations: Total number of recommendations included.
    """

    generated_at: datetime = field(default_factory=datetime.utcnow)
    recommendations: list[Recommendation] = field(default_factory=list)
    summary: str = ""
    total_recommendations: int = 0
