"""Data model for a recommendation generated by a Marcos OS executive."""

from dataclasses import dataclass


@dataclass
class Recommendation:
    """A single actionable recommendation produced by an executive.

    Attributes:
        title: Short headline describing the recommended action.
        description: Full explanation of what should be done and why.
        category: The life domain this recommendation belongs to
            (e.g. "Marriage", "Finance", "Home").
        priority: Integer priority where 1 is highest. Derived from the
            priority model defined in the Memory Layer specification.
        reasoning: The logic or observation that triggered this recommendation.
        executive: Name of the executive that produced this recommendation.
        confidence: Float between 0.0 and 1.0 indicating how confident the
            executive is in this recommendation.
    """

    title: str
    description: str
    category: str
    priority: int
    reasoning: str
    executive: str
    confidence: float
