"""Memory object representing a discrete actionable task."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class Task:
    """A single discrete action that needs to be completed.

    Tasks are more granular than commitments and may be generated by
    executives or created by Marcos directly. A commitment may be broken
    into one or more tasks by the Memory Layer.

    Attributes:
        id: Unique identifier. Will map to a UUID primary key in PostgreSQL.
        title: Short action description.
        description: Full context.
        status: Lifecycle state — 'pending', 'in_progress', 'completed', 'cancelled'.
        priority: Integer priority (1 = highest).
        created_at: Timestamp when the task was created.
        due_at: Optional deadline.
        completed_at: Timestamp when the task was completed.
        commitment_id: Optional reference to a parent Commitment.
        domain: Life domain this task belongs to.
        estimated_minutes: Optional time estimate in minutes.
    """

    id: str
    title: str
    description: str = ""
    status: str = "pending"
    priority: int = 5
    created_at: datetime = field(default_factory=datetime.utcnow)
    due_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    commitment_id: Optional[str] = None
    domain: str = ""
    estimated_minutes: Optional[int] = None

    def is_overdue(self) -> bool:
        """Return True if the task is past its due date and not resolved."""
        if self.due_at is None:
            return False
        if self.status in ("completed", "cancelled"):
            return False
        return datetime.utcnow() > self.due_at
